services:
  postgres:
    image: postgres:16
    container_name: voting_postgres
    environment:
      POSTGRES_DB: voting_system
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - voting-service_pgdata:/var/lib/postgresql/data

volumes:
  voting-service_pgdata:
