spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/voting_system
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

springdoc:
  swagger-ui:
    path: /swagger-ui.html

resilience4j:
  retry:
    instances:
      cpfValidation:
        max-attempts: 2
        wait-duration: 500ms
        retry-exceptions:
          - feign.FeignException
        ignore-exceptions:
          - org.voting.exception.BusinessException

